defaults:
  - _self_

hydra:
  run:
    dir: .
  job:
    chdir: false

data:
  batch_size: 2048
  num_workers: 4
  pin_memory: true
  flatten_branch: true
  dtype: float32
  train:
    data_path: train/data/deeponet_terzaghi_train.h5
    seed: 42
    shuffle: false
    drop_last: false
  val:
    data_path: train/data/deeponet_terzaghi_val.h5
    seed: 43
    shuffle: false
    drop_last: false

model:
  use_conv_branch: false      # true for Conv2d branch (requires flatten_branch=false)
  use_fourier_features: true  # false to disable Fourier features
  branch:
    input_dim: 2601  # 51 * 51 (ignored if use_conv_branch=true)
    hidden_dim: 256
    output_dim: 128
    num_blocks: 3
  trunk:
    input_dim: 256
    hidden_dim: 256
    output_dim: 128
    num_blocks: 3
  ff_features: 128
  ff_sigma: 1.0
  dtype: float32
  device: ${training.device}

training:
  epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.0001
  checkpoint_dir: train/checkpoint
  log_dir: train/runs/deeponet
  resume: false
  print_every: 2
  checkpoint_interval: 1
  grad_clip_norm: null
  device: cuda
  log_every_steps: 10
  verbose: false
